### ISSUE TITLE
Not able to call "downloadDataWithAuthenticationToken" with iOS 8

### ISSUE THREAD

**Issue by kev52** [idoodler/POEditor#1]
Hi is this library ready for iOS 8? I'm not able to initialize it. There is always an exception like:

Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '**\* setObjectForKey: key cannot be nil'

**Comment by idoodler** [comment]
Hi, sorry for the late reply. I am using it on iOS 8.1.2 without any problem, but I have a slightly adopted version. I will add all the changes ASAP.

Thanks for reporting!

**Comment by kev52** [comment]
Are there any news on it?

**Comment by idoodler** [comment]
Issue has been fixed now, I also tested it in iOS 8.1.2 and iOS 8.1.3
